export const GET_ERRORS = 'GET_ERRORS';
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
export const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const CLEAR_REGISTER_ERRORS = 'CLEAR_ERREGISTER_RORS';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_CANCEL = 'USER_LOGIN_REQUEST_CANCEL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE';
export const GET_CURRENT_USER_PROFILE_ERRORS = 'GET_CURRENT_USER_PROFILE_ERRORS';
export const SET_CURRENT_USER_PROFILE = 'SET_CURRENT_USER_PROFILE';

export const CURRENT_USER_PROFILE_UPDATE_REQUEST = 'CURRENT_USER_PROFILE_UPDATE_REQUEST';
export const CURRENT_USER_PROFILE_UPDATE_ERRORS = 'CURRENT_USER_PROFILE_UPDATE_ERRORS';
export const CURRENT_USER_PROFILE_UPDATE_SUCCESS = 'CURRENT_USER_PROFILE_UPDATE_SUCCESS';