export const GET_ERRORS = 'GET_ERRORS';
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
export const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const CLEAR_REGISTER_ERRORS = 'CLEAR_REGISTER_ERRORS';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_CANCEL = 'USER_LOGIN_REQUEST_CANCEL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const SET_CURRENT_USER_REQUEST = 'SET_CURRENT_USER_REQUEST';
export const SET_CURRENT_USER_ERRORS = 'SET_CURRENT_USER_ERRORS';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';