export const CONNECTION_COUNT_REQUEST = 'CONNECTION_COUNT_REQUEST';
export const CONNECTION_COUNT_ERRORS = 'CONNECTION_COUNT_ERRORS';
export const CONNECTION_COUNT_SUCCESS = 'CONNECTION_COUNT_SUCCESS';

export const CONNECTIONS_REQUEST = 'CONNECTIONS_REQUEST';
export const CONNECTIONS_ERRORS = 'CONNECTIONS_ERRORS';
export const CONNECTIONS_SUCCESS = 'CONNECTIONS_SUCCESS';

export const PENDING_REQUEST_COUNT_REQUEST = 'PENDING_REQUEST_COUNT_REQUEST';
export const PENDING_REQUEST_COUNT_ERRORS = 'PENDING_REQUEST_COUNT_ERRORS';
export const PENDING_REQUEST_COUNT_SUCCESS = 'PENDING_REQUEST_COUNT_SUCCESS';

export const PENDING_REQUEST_REQUEST = 'PENDING_REQUEST_REQUEST';
export const PENDING_REQUEST_ERRORS = 'PENDING_REQUEST_ERRORS';
export const PENDING_REQUEST_SUCCESS = 'PENDING_REQUEST_SUCCESS';

export const APPROVE_CONNECTION_REQUEST = 'APPROVE_CONNECTION_REQUEST';
export const APPROVE_CONNECTION_ERRORS = 'APPROVE_CONNECTION_ERRORS';
export const APPROVE_CONNECTION_SUCCESS = 'APPROVE_CONNECTION_SUCCESS';

export const DECLINE_CONNECTION_REQUEST = 'DECLINE_CONNECTION_REQUEST';
export const DECLINE_CONNECTION_ERRORS = 'DECLINE_CONNECTION_ERRORS';
export const DECLINE_CONNECTION_SUCCESS = 'DECLINE_CONNECTION_SUCCESS';

export const REMOVE_CONNECTION_REQUEST = 'REMOVE_CONNECTION_REQUEST';
export const REMOVE_CONNECTION_ERRORS = 'REMOVE_CONNECTION_ERRORS';
export const REMOVE_CONNECTION_SUCCESS = 'REMOVE_CONNECTION_SUCCESS';

export const ADD_CONNECTION_REQUEST = 'ADD_CONNECTION_REQUEST';
export const ADD_CONNECTION_ERRORS = 'ADD_CONNECTION_ERRORS';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';

export const CONNECTION_STATUS_REQUEST = 'CONNECTION_STATUS_REQUEST';
export const CONNECTION_STATUS_ERRORS = 'CONNECTION_STATUS_ERRORS';
export const CONNECTION_STATUS_SUCCESS = 'CONNECTION_STATUS_SUCCESS';

export const CONNECTION_COUNT_BY_USER_ID_REQUEST = 'CONNECTION_COUNT_BY_USER_ID_REQUEST';
export const CONNECTION_COUNT_BY_USER_ID_ERRORS = 'CONNECTION_COUNT_BY_USER_ID_ERRORS';
export const CONNECTION_COUNT_BY_USER_ID_SUCCESS = 'CONNECTION_COUNT_BY_USER_ID_SUCCESS';