export const FILE_SINGLE_UPLOAD_REQUEST = 'FILE_SINGLE_UPLOAD_REQUEST';
export const FILE_SINGLE_UPLOAD_ERRORS = 'FILE_SINGLE_UPLOAD_ERRORS';
export const FILE_SINGLE_UPLOAD_SUCCESS = 'FILE_SINGLE_UPLOAD_SUCCESS';