export const FILE_SINGLE_UPLOAD_REQUEST = 'FILE_SINGLE_UPLOAD_REQUEST';
export const FILE_SINGLE_UPLOAD_ERRORS = 'FILE_SINGLE_UPLOAD_ERRORS';
export const FILE_SINGLE_UPLOAD_SUCCESS = 'FILE_SINGLE_UPLOAD_SUCCESS';

export const FILE_GET_DOWNLOAD_URL_REQUEST = 'FILE_GET_DOWNLOAD_URL_REQUEST';
export const FILE_GET_DOWNLOAD_URL_ERRORS = 'FILE_GET_DOWNLOAD_URL_ERRORS';
export const FILE_GET_DOWNLOAD_URL_SUCCESS = 'FILE_GET_DOWNLOAD_URL_SUCCESS';