export const ROOMS_REQUEST = 'ROOMS_REQUEST';
export const ROOMS_ERRORS = 'ROOMS_ERRORS';
export const ROOMS_SUCCESS = 'ROOMS_SUCCESS';

export const MESSAGES_BY_ROOM_ID_REQUEST = 'MESSAGES_BY_ROOM_ID_REQUEST';
export const MESSAGES_BY_ROOM_ID_ERRORS = 'MESSAGES_BY_ROOM_ID_ERRORS';
export const MESSAGES_BY_ROOM_ID_SUCCESS = 'MESSAGES_BY_ROOM_ID_SUCCESS';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';