export const CURRENT_USER_POSTS_REQUEST = 'CURRENT_USER_POSTS_REQUEST';
export const CURRENT_USER_POSTS_ERRORS = 'CURRENT_USER_POSTS_ERRORS';
export const CURRENT_USER_POSTS_SUCCESS = 'CURRENT_USER_POSTS_SUCCESS';

export const CURRENT_USER_POSTS_CREATE_REQUEST = 'CURRENT_USER_POSTS_CREATE_REQUEST';
export const CURRENT_USER_POSTS_CREATE_ERRORS = 'CURRENT_USER_POSTS_CREATE_ERRORS';
export const CURRENT_USER_POSTS_CREATE_SUCCESS = 'CURRENT_USER_POSTS_CREATE_SUCCESS';

export const CURRENT_USER_POSTS_DELETE_REQUEST = 'CURRENT_USER_POSTS_DELETE_REQUEST';
export const CURRENT_USER_POSTS_DELETE_ERRORS = 'CURRENT_USER_POSTS_DELETE_ERRORS';
export const CURRENT_USER_POSTS_DELETE_SUCCESS = 'CURRENT_USER_POSTS_DELETE_SUCCESS';

export const CURRENT_USER_POSTS_LIKE_TOGGLE_REQUEST = 'CURRENT_USER_POSTS_LIKE_TOGGLE_REQUEST';
export const CURRENT_USER_POSTS_LIKE_TOGGLE_ERRORS = 'CURRENT_USER_POSTS_LIKE_TOGGLE_ERRORS';
export const CURRENT_USER_POSTS_LIKE_TOGGLE_SUCCESS = 'CURRENT_USER_POSTS_LIKE_TOGGLE_SUCCESS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_ERRORS = 'CREATE_COMMENT_ERRORS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';