export const CURRENT_USER_POSTS_REQUEST = 'CURRENT_USER_POSTS_REQUEST';
export const CURRENT_USER_POSTS_ERRORS = 'CURRENT_USER_POSTS_ERRORS';
export const CURRENT_USER_POSTS_SUCCESS = 'CURRENT_USER_POSTS_SUCCESS';

export const CURRENT_USER_POST_COUNT_REQUEST = 'CURRENT_USER_POST_COUNT_REQUEST';
export const CURRENT_USER_POST_COUNT_ERRORS = 'CURRENT_USER_POST_COUNT_ERRORS';
export const CURRENT_USER_POST_COUNT_SUCCESS = 'CURRENT_USER_POST_COUNT_SUCCESS';

export const CURRENT_USER_POSTS_CREATE_REQUEST = 'CURRENT_USER_POSTS_CREATE_REQUEST';
export const CURRENT_USER_POSTS_CREATE_ERRORS = 'CURRENT_USER_POSTS_CREATE_ERRORS';
export const CURRENT_USER_POSTS_CREATE_SUCCESS = 'CURRENT_USER_POSTS_CREATE_SUCCESS';

export const CURRENT_USER_POSTS_DELETE_REQUEST = 'CURRENT_USER_POSTS_DELETE_REQUEST';
export const CURRENT_USER_POSTS_DELETE_ERRORS = 'CURRENT_USER_POSTS_DELETE_ERRORS';
export const CURRENT_USER_POSTS_DELETE_SUCCESS = 'CURRENT_USER_POSTS_DELETE_SUCCESS';

export const CURRENT_USER_POSTS_LIKE_TOGGLE_REQUEST = 'CURRENT_USER_POSTS_LIKE_TOGGLE_REQUEST';
export const CURRENT_USER_POSTS_LIKE_TOGGLE_ERRORS = 'CURRENT_USER_POSTS_LIKE_TOGGLE_ERRORS';
export const CURRENT_USER_POSTS_LIKE_TOGGLE_SUCCESS = 'CURRENT_USER_POSTS_LIKE_TOGGLE_SUCCESS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_ERRORS = 'CREATE_COMMENT_ERRORS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const POSTS_BY_USER_ID_REQUEST = 'POSTS_BY_USER_ID_REQUEST';
export const POSTS_BY_USER_ID_ERRORS = 'POSTS_BY_USER_ID_ERRORS';
export const POSTS_BY_USER_ID_SUCCESS = 'POSTS_BY_USER_ID_SUCCESS';

export const POST_COUNT_BY_USER_ID_REQUEST = 'POST_COUNT_BY_USER_ID_REQUEST';
export const POST_COUNT_BY_USER_ID_ERRORS = 'POST_COUNT_BY_USER_ID_ERRORS';
export const POST_COUNT_BY_USER_ID_SUCCESS = 'POST_COUNT_BY_USER_ID_SUCCESS';

export const CREATE_COMMENT_ON_VISIT_REQUEST = 'CREATE_COMMENT_ON_VISIT_REQUEST';
export const CREATE_COMMENT_ON_VISIT_ERRORS = 'CREATE_COMMENT_ON_VISIT_ERRORS';
export const CREATE_COMMENT_ON_VISIT_SUCCESS = 'CREATE_COMMENT_ON_VISIT_SUCCESS';

export const POST_LIKE_TOGGLE_ON_VISIT_REQUEST = 'POST_LIKE_TOGGLE_ON_VISIT_REQUEST';
export const POST_LIKE_TOGGLE_ON_VISIT_ERRORS = 'POST_LIKE_TOGGLE_ON_VISIT_ERRORS';
export const POST_LIKE_TOGGLE_ON_VISIT_SUCCESS = 'POST_LIKE_TOGGLE_ON_VISIT_SUCCESS';

export const POST_RESIZED_IMG_URL_UPDATE_REQUEST = 'POST_RESIZED_IMG_URL_UPDATE_REQUEST';
export const POST_RESIZED_IMG_URL_UPDATE_ERRORS = 'POST_RESIZED_IMG_URL_UPDATE_ERRORS';
export const POST_RESIZED_IMG_URL_UPDATE_SUCCESS = 'POST_RESIZED_IMG_URL_UPDATE_SUCCESS';