export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE';
export const GET_CURRENT_USER_PROFILE_ERRORS = 'GET_CURRENT_USER_PROFILE_ERRORS';
export const SET_CURRENT_USER_PROFILE = 'SET_CURRENT_USER_PROFILE';

export const CURRENT_USER_PROFILE_UPDATE_REQUEST = 'CURRENT_USER_PROFILE_UPDATE_REQUEST';
export const CURRENT_USER_PROFILE_UPDATE_ERRORS = 'CURRENT_USER_PROFILE_UPDATE_ERRORS';
export const CURRENT_USER_PROFILE_UPDATE_SUCCESS = 'CURRENT_USER_PROFILE_UPDATE_SUCCESS';

export const CURRENT_USER_EXPERIENCES_REQUEST = 'CURRENT_USER_EXPERIENCES_REQUEST';
export const CURRENT_USER_EXPERIENCES_ERRORS = 'CURRENT_USER_EXPERIENCES_ERRORS';
export const CURRENT_USER_EXPERIENCES_SUCCESS = 'CURRENT_USER_EXPERIENCES_SUCCESS';

export const CURRENT_USER_EDUCATION_REQUEST = 'CURRENT_USER_EDUCATION_REQUEST';
export const CURRENT_USER_EDUCATION_ERRORS = 'CURRENT_USER_EDUCATION_ERRORS';
export const CURRENT_USER_EDUCATION_SUCCESS = 'CURRENT_USER_EDUCATION_SUCCESS';

export const GET_PROFILE_BY_USER_ID_REQUEST = 'GET_PROFILE_BY_USER_ID_REQUEST';
export const GET_PROFILE_BY_USER_ID_ERRORS = 'GET_PROFILE_BY_USER_ID_ERRORS';
export const GET_PROFILE_BY_USER_ID_SUCCESS = 'GET_PROFILE_BY_USER_ID_SUCCESS';

export const CHAT_PROFILE_REQUEST = 'CHAT_PROFILE_REQUEST';
export const CHAT_PROFILE_ERRORS = 'CHAT_PROFILE_ERRORS';
export const CHAT_PROFILE_SUCCESS = 'CHAT_PROFILE_SUCCESS';