export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE';
export const GET_CURRENT_USER_PROFILE_ERRORS = 'GET_CURRENT_USER_PROFILE_ERRORS';
export const SET_CURRENT_USER_PROFILE = 'SET_CURRENT_USER_PROFILE';

export const CURRENT_USER_PROFILE_UPDATE_REQUEST = 'CURRENT_USER_PROFILE_UPDATE_REQUEST';
export const CURRENT_USER_PROFILE_UPDATE_ERRORS = 'CURRENT_USER_PROFILE_UPDATE_ERRORS';
export const CURRENT_USER_PROFILE_UPDATE_SUCCESS = 'CURRENT_USER_PROFILE_UPDATE_SUCCESS';

export const CURRENT_USER_EXPERIENCES_REQUEST = 'CURRENT_USER_EXPERIENCES_REQUEST';
export const CURRENT_USER_EXPERIENCES_ERRORS = 'CURRENT_USER_EXPERIENCES_ERRORS';
export const CURRENT_USER_EXPERIENCES_SUCCESS = 'CURRENT_USER_EXPERIENCES_SUCCESS';

export const CURRENT_USER_EDUCATION_REQUEST = 'CURRENT_USER_EDUCATION_REQUEST';
export const CURRENT_USER_EDUCATION_ERRORS = 'CURRENT_USER_EDUCATION_ERRORS';
export const CURRENT_USER_EDUCATION_SUCCESS = 'CURRENT_USER_EDUCATION_SUCCESS';