export const QUERY_REQUEST = 'QUERY_REQUEST';
export const QUERY_ERRORS = 'QUERY_ERRORS';
export const QUERY_SUCCESS = 'QUERY_SUCCESS';

export const SET_COMPANY_FILTER = 'SET_COMPANY_FILTER';
export const SET_LOCATION_FILTER = 'SET_LOCATION_FILTER';
